ecmwf-ifs/dwarf-p-cloudsc

src/cloudsc_loki/CMakeLists.txt

My last attempt at fixing these race conditions did not reach far enough for OMNI.
This makes now sure that each target uses the target's bin-directory to store newly generated xmods, thus avoiding the issue in parallel builds.

[Loki] Make sure each target uses a bespoke XMOD directory

---

.github/scripts/run-targets.sh
.github/workflows/build.yml
README.md
src/cloudsc_gpu/dwarf_cloudsc_gpu.F90

This adds an additional step in the build workflow to validate results for a small set of columns (100) for double precision binaries.
Notably, they currently show very small deviations on Github which aren't present on leap42 with same compiler version. Small enough though to not be flagged by the validation module. Will investigate this on a separate occasion as it is currently not reproducible locally.

Validate results for targets in Github actions

---

.github/scripts/bootstrap-nvhpc.sh
.github/scripts/install-hdf5.sh
.github/scripts/run-targets.sh
.github/workflows/build.yml
arch/github/ubuntu/nvhpc/21.9/env.sh
arch/github/ubuntu/nvhpc/21.9/toolchain.cmake
arch/toolchains/github-ubuntu-nvhpc.cmake

Small addition to our Github actions configuration that verifies builds with NVHPC using the bootstrap script from Atlas.
This can't actually validate results as we can't run the GPU variants but might highlight compile-time problems, in particular with OpenACC annotations, early on.
Takes a bit longer than the other jobs as it needs to download nvhpc and compile hdf5 from source (which takes ~3 and 10 mins, respectively).

Test NVHPC in Github actions

---

src/cloudsc_c/cloudsc/cloudsc_c.c

This was introduced in d88c0c8f8d1effd5bd395cb71657629fb242f661 to mirror
Fortran reference results. The bug was fixed in the Fortran variants in
bac8d631f017a391ee8441309247eadd51dca637 and reference results updated
but the fix was not applied to the C variant at that time.

Remove the precision bug from the C variant

---

src/cloudsc_loki/cloudsc_loki.config

An update for the Loki configuration in line with Loki PR #134.

Use type name instead of variable name for type-bound procedures

---

.github/workflows/build.yml
arch/github/ubuntu/gnu/9.4.0/env.sh

Github is transitioning ubuntu-latest to 22.04 runner images and so we end up with different compiler versions randomly. This should make sure we are using GNU 9.4 every time.

Hotfix: Use 20.04 runner image and make sure GNU 9.4 is installed

---

arch/toolchains/ecmwf-hpc2020-intel.cmake

Add compiler flags to be inline with the IFS. The intention is to create a better baseline for benchmarking CloudSC.

Add compiler flags to be inline with the IFS

---

src/common/module/yoethf.F90
src/prototype1/cloudsc/cloudsc_driver.F90

Fixes to compile and run the develop branch of CLOUDSC on Mac M1 with gfortran: 1) added missing omp declarations and 2) specifically requested endiannes conversion when opening Fortran tape by a "Prototype" dwarf version (unofficial functionality of Fortran compilers, trick as suggested by WD).

Minor fixes to compile and run the dwarf on Mac M1

---

arch/ecmwf/hpc2020/nvhpc/22.11/env.sh
arch/ecmwf/hpc2020/nvhpc/22.11/toolchain.cmake
arch/toolchains/ecmwf-hpc2020-nvhpc.cmake
src/cloudsc_gpu/CMakeLists.txt
src/cloudsc_loki/CMakeLists.txt
src/common/CMakeLists.txt
src/common/module/cloudsc_field_state_mod.F90
src/common/module/yomphyder.F90

This adds the gvmode (gang-vector-mode) flag for NVHPC on HPC2020, and adds updated arch files for nvidia/22.11

Enable gvmode and add nvidia/22.11 arch files

---

.github/scripts/verify-targets.sh
.github/workflows/build.yml
bundle.yml
src/cloudsc_fortran_atlas/CMakeLists.txt
src/common/module/cloudsc_mpi_mod.F90

As mentioned in the review of #54, this adds Atlas and its dependencies as optional projects to the bundle.
By default, they are not being built, which should allow to pick up an existing Atlas installation as usual. `--with-atlas` will enable building `eckit`, `fckit` and `atlas`. By default, tests are disabled for these dependencies but can be enabled using `--with-dependency-tests`.
I have also enabled Github actions integration for the new variant.

Bundle integration for Atlas

---

src/cloudsc_loki/cloudsc_cuf_loki.config
src/cloudsc_loki/cloudsc_loki.config

Small update to the Loki configurations that is synced with the Scheduler update in PR 191: https://github.com/ecmwf-ifs/loki/pull/191
Importantly, this includes some specific transformation-configuration logic for the SCC-CUF transformations family.

Loki config update

---

README.md
arch/ecmwf/hpc2020/intel-sycl/2021.4.0/env.sh
arch/ecmwf/hpc2020/intel-sycl/2021.4.0/toolchain.cmake
arch/toolchains/ecmwf-hpc2020-intel-sycl.cmake
bundle.yml

Additional encoding of the build settings in a dedicated env with a custom DPCPP install, and a short README description.
Note, it's nothing fancy but it should be enough to make it easily accessible.

SYCL-specific env and README entry

---

src/cloudsc_cuda/cloudsc/cloudsc_driver.cu
src/cloudsc_cuda/cloudsc/cloudsc_driver_hoist.cu

Adding metric col/s as metric for CUDA variants (same thing done as for HIP and SYCL variants)

Cuda update: metric col/s

---

src/cloudsc_loki/CMakeLists.txt

Necessary changes to make [Loki PR 208](https://github.com/ecmwf-ifs/loki/pull/208) work.

Loki F2C using `loki_transform` instead of `loki_transform_transpile`

---

.github/scripts/verify-targets.sh
CMakeLists.txt
src/cloudsc_c/CMakeLists.txt
src/cloudsc_c/cloudsc/cloudsc_validate.c
src/cloudsc_c/cloudsc/cloudsc_validate.h
src/cloudsc_c/cloudsc/load_state.c

**Draft/POC implementation HDF5 input and reference reading for C-style variants to not rely on serialbox for those variants.**
Before I am tempted to over-engineer this I thought I'd make a Draft PR to allow for some comments/feedback and to allow a discussion about a potential restructuring/refactoring of the C-style variants. 
Tested on 
* **AC** with Intel and NVHPC
* **LUMI** via cray toolchain 
Obviously more testing necessary before thinking about merging this.
Some hacks in the CMakeLists.txt due to problems with HDF5 on AC.

Emancipation from serialbox via HDF5 for C-style variants

---

src/cloudsc_loki/cloudsc_cuf_loki.config
src/cloudsc_loki/cloudsc_loki.config

This is an alternative solution to #79.
* re-enables chasing import dependencies (after the last-minute default behaviour change in Loki) 
* fixes the problem that the header module defining `NCLV`, which is required for variable demotion, was marked as blocked and not ignored
Performance looks good with this, and demotion verified by diff'ing against the gpu_scc variant:
```
$ NV_ACC_CUDA_HEAPSIZE=6G bin/dwarf-cloudsc-loki-scc 1 163840 128
NUMPROC=1, NUMOMP=1, NGPTOTG=163840, NPROMA=128, NGPBLKS=1280
Reference MFLOP count for 100 columns :  12.48232900
NUMOMP    NGPTOT  #GP-cols     #BLKS    NPROMA tid# : Time(msec)  MFlops/s     col/s
1    163840    163840         1       128    0 :        105    194538   1558509 @ rank#0:core#172
1    163840    163840      1280       128   -1 : …
```

Loki: enable imports and mark headers as ignored instead of blocked

---

src/cloudsc_loki/cloudsc_loki.config

An annoying oversight: OMNI has become broken with v1.5.1 due to yoecldp.F90 being now parsed (it was on the block list previously) but the OMNI frontend segfaulting on it... Testing did not pick up on this, because CLOUDSC tests use only Fparser, and Loki regression wasn't tested against the configuration changes until after the release.
This PR ensures that file is always parsed with FParser

Ensure yoecldp.F90 is parsed with FParser

---

bundle.yml

Another annoying oversight: The correct field-api tag name is `v0.3.0` (and not `0.3.0`). But the field-api project was marked as optional (to gracefully ignore that the field-api dependency could not be downloaded when it was still hosted internally). With field-api now available on Github, it should no longer be necessary to mark it as optional, ensuring we fail in the bundle creation when a tag is invalid.

Mark projects no longer as optional and fix field-api to v0.3.0

---

src/cloudsc_cuda/cloudsc/dtype.h

Use single precision math functions for CUDA variants when compiling for single precision, thus:
* `pow` -> `powf`
* `fabs` -> `fabsf`

Use single precision math functions for CUDA variants

---

CMakeLists.txt
README.md
arch/toolchains/github-ubuntu-nvhpc.cmake
src/cloudsc_cuda/CMakeLists.txt
src/cloudsc_cuda/cloudsc/cloudsc_c_opt.cu
src/cloudsc_cuda/cloudsc/cloudsc_c_opt.h
src/cloudsc_cuda/cloudsc/cloudsc_driver_opt.cu
src/cloudsc_cuda/cloudsc/cloudsc_driver_opt.h

Optimisation beyond k-caching:
* buffering variables
* pipelined global-to-shared memory copies overlapped with compute, TMA loads
* [NVIDIA blog post: Controlling Data Movement to Boost Performance on the NVIDIA Ampere Architecture](https://developer.nvidia.com/blog/controlling-data-movement-to-boost-performance-on-ampere-architecture/) 
likely still potential for further optimisation ...
Implemented with input from @lukasm91
_________
k-caching vs "opt"-variant performance (compiled with nvhpc 22.11 and executed with `1 262144 128`):
* **double-precision**
* k-caching: 600 - 700 GF/s
* "opt": 700 - 850 GF/s
* **single-precision**
* k-caching: 2300 - 3000 GF/s
* "opt": 2700 - 5000 GF/s

CUDA variant optimised beyond k-caching

---

src/cloudsc_c/cloudsc/load_state.c
src/cloudsc_cuda/cloudsc/load_state.cu
src/cloudsc_hip/cloudsc/load_state.cpp
src/cloudsc_sycl/cloudsc/load_state.cpp

Some of the HDF5-related functions request more rights than necessary in sections that only read the state. This PR adjusts the rights in the corresponding `H5Fopen` function calls.
While it is not fundamentally wrong to request RDWR access here, HDF5 applies a file lock in this case, which can lead to errors if multiple of the cloudsc prototypes are run simultaneously, for example in a benchmark setting. The lock-induced errors look like this:
```
[...]
HDF5-DIAG: Error detected in HDF5 (1.14.3) thread 0:
#000: [...]/src/H5F.c line 836 in H5Fopen(): unable to synchronously open file
major: File accessibility
minor: Unable to open file
[...]
```
Note that file locking can also be disabled altogether by setting the environment variable `HDF5_USE_FILE_LOCKING=FALSE`,  but users might not be …

HDF5 file access rights

---

src/cloudsc_loki/cloudsc_loki.config

This PR adds a new C-transpilation pipeline to the Loki configuration file that replaces the previous use of the implicit entry point for the `FortranCTransformation` in `loki-transform.py convert`. It does this by adding a new entry for the `FortranISOCWrapperTransformation` and marking the corresponding modules with `"header"` roles.
Integration note: This PR requires Loki PR #464 (https://github.com/ecmwf-ifs/loki/pull/464) to be merged first, and currently points to this branch in a temporary head commit that should be removed before merging.

Loki: C transpilation from pipeline in config file
